### ISSUE TITLE
Regarding LTS and urgent fixes

### ISSUE THREAD

**Issue by Heshma** [corretto/corretto-11-docker#12]
From the support documentation( https://aws.amazon.com/corretto/faqs/#support ) it is evident that 'Updates are planned to be released quarterly. Amazon also plans to apply urgent fixes (including security) outside of the regular quarterly cycle when they are available and ready to use.'

If we raise an issue on github , will a build be released with the fixes in between the regular quarterly updates?

**Comment by EricEdens** [comment]
Security is our highest priority, and as discussed in the FAQ, we will release fixes as soon as possible. If you have a security issue, please report it by email to aws-security@amazon.com, rather than via a public mechanism such as a GitHub issue.

For non-urgent issues, we will triage and release fixes outside quarterly releases on a case-by-case basis.
