### ISSUE TITLE
LANG, LC_ALL and HOSTNAME set to values different than expected

### ISSUE THREAD

**Issue by AzeemJiva** [corretto/corretto-11-docker#20]
# Describe the bug
Per this thread:

https://twitter.com/alvaro_sanchez/status/1217744732065091584?s=21

LANG, LC_ALL and HOSTNAME are all set to values that are not expected or default. 

### To Reproduce
Steps and (source) code to reproduce the behavior.

### Expected behavior
HOSTNAME should be set to localhost
LANG should be set to en_US.utf-8 
LC_ALL should be set to en_US.utf-8

### Platform information
    OS:  Docker
    Version Corretto 8 and 11 latest

**Comment by davecurrie** [comment]
The biggest question for me is whether changing what is default AL2 Docker image behavior in the Corretto image will affect others that are expecting AL2 default behavior i.e. is this "broken" vs is it "inconvenient for building Micronaut".

BTW, @alvarosanchez we're really excited that Micronaut is also building with Corretto. :)

**Comment by alvarosanchez** [comment]
Sure, I didn't initiate the request to change anything, and am happy with the workarounds I used in the GitHub Actions workflow, as they make everything behave correctly. Thanks!

**Comment by navyxliu** [comment]
I tried corretto-11 docker images. It doesn't set LANG/LC_ALL. 

docker run -it --rm amazoncorretto:11 /bin/bash
```
bash-4.2# echo $HOSTNAME
7541e6da323e
bash-4.2# echo $LANG

bash-4.2# echo $LC_ALL

```
HOSTNAME shouldn't be empty.  The current behavior  is correct.

**Comment by patrykorwat** [comment]
I ask to reopen the issue and add `LANG` with value `en_US.utf8`.

Lack of encoding values leads `Charset.defaultCharset()` to return `US-ASCII` instead of commonly acceptable `UTF-8`. Default character is used in e.g. `docker-library/openjdk`, which are often used to deploy code.

The current configuration breaks code that assumes default encoding set to UTF-8. The change does not break code that assumes `US-ASCII` default encoding since ASCII is a subset of UTF-8.

The issue has been talked in corretto/corretto-8-docker#24 and docker-library/openjdk#32, amazonlinux/container-images#36.

That issue leads to problems like one described in #22.
