### ISSUE TITLE
Compilation throws unmappable character for encoding US-ASCII

### ISSUE THREAD

**Issue by mpaluchowski** [corretto/corretto-11-docker#22]
We're trying to use the containers to build our code, which includes UTF-8 characters. We're getting errors of the sort:

```
error: unmappable character (0xBC) for encoding US-ASCII
```

for strings:

```
"Twój kod do konta to: " + token.value() + ". Kod jest ważny przez najbliższe 30 minut."
```

**Comment by yoroto** [comment]
0xBC is not in US-ASCII. You need to use a different encoding.

**Comment by alvdavi** [comment]
Hi, I have checked and 0xBC maps to one half of the UTF-8 encoding for character `ż`(0xC5BC) (confirming the encoding is UTF-8 and not a different 8bit codepage). I hope this helps

**Comment by mpaluchowski** [comment]
All characters we have in our code are valid UTF-8. The code compiles fine everywhere, including inside containers based on `openjdk` official images. The problem is only with `corretto` containers.

**Comment by patrykorwat** [comment]
@yoroto @alvdavi As mentioned in #20, the issue is caused by lack of default encoding of this Docker image set to UTF-8, which is basically a standard configuration that is in e.g. OpenJDK Docker images.

I'm well aware any it's a standard in Java not to rely on default encoding but not everyone knows that, which it leads to confusion and misunderstanding.

**Comment by navyxliu** [comment]
@meshuga I agree with you.  I will send a PR about it.

**Comment by navyxliu** [comment]
We also apply this patch to corretto-docker.
